// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float4> RWSHBuffer;
TextureCube _CubeResource;
SamplerState sampler_CubeResource;
//samplerCUBE CubeResource;

#define PI 3.14159265358
#define Y0(v) (1.0 / 2.0) * sqrt(1.0 / PI)
#define Y1(v) sqrt(3.0 / (4.0 * PI)) * v.z
#define Y2(v) sqrt(3.0 / (4.0 * PI)) * v.y
#define Y3(v) sqrt(3.0 / (4.0 * PI)) * v.x
#define Y4(v) 1.0 / 2.0 * sqrt(15.0 / PI) * v.x * v.z
#define Y5(v) 1.0 / 2.0 * sqrt(15.0 / PI) * v.z * v.y
#define Y6(v) 1.0 / 4.0 * sqrt(5.0 / PI) * (-v.x * v.x - v.z * v.z + 2 * v.y * v.y)
#define Y7(v) 1.0 / 2.0 * sqrt(15.0 / PI) * v.y * v.x
#define Y8(v) 1.0 / 4.0 * sqrt(15.0 / PI) * (v.x * v.x - v.z * v.z)
#define Y9(v) 1.0 / 4.0 * sqrt(35.0 / (2.0 * PI)) * (3 * v.x * v.x - v.z * v.z) * v.z
#define Y10(v) 1.0 / 2.0 * sqrt(105.0 / PI) * v.x * v.z * v.y
#define Y11(v) 1.0 / 4.0 * sqrt(21.0 / (2.0 * PI)) * v.z * (4 * v.y * v.y - v.x * v.x - v.z * v.z)
#define Y12(v) 1.0 / 4.0 * sqrt(7 / PI) * v.y * (2 * v.y * v.y - 3 * v.x * v.x - 3 * v.z * v.z)
#define Y13(v) 1.0 / 4.0 * sqrt(21.0 / (2.0 * PI)) * v.x * (4 * v.y * v.y - v.x * v.x - v.z * v.z)
#define Y14(v) 1.0 / 4.0 * sqrt(105.0 / PI) * (v.x * v.x - v.z * v.z) * v.y
#define Y15(v) 1.0 / 4.0 * sqrt(35.0 / (2 * PI)) * (v.x * v.x - 3 * v.z * v.z) * v.x

float4 UniformSampleSphere(float2 E)
{
    float Phi = 2 * PI * E.x;
    float CosTheta = 1 - 2 * E.y;
    float SinTheta = sqrt(1 - CosTheta * CosTheta);
    
    float3 H;
    H.x = SinTheta * cos(Phi);
    H.y = SinTheta * sin(Phi);
    H.z = CosTheta;
    
    float PDF = 1.0 / (4 * PI);

    return float4(H, PDF);
}

float hash(float3 p)
{
    p = frac(p * 0.3183099 + 0.1);
    p *= 17.0;
    return frac(p.x * p.y * p.z * (p.x + p.y + p.z));
}

[numthreads(16, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int SampleNum = 1000;
    
    float weight = 4.0f * PI;
    float factor = weight / SampleNum;
    
    float4 Init = float4(0, 0, 0, 0);
    float4 coefs[16] = { Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init, Init };
    
    for (int i = 0; i < SampleNum; i++)
    {
        float x = hash(i);
        float y = hash(i + id.x);
        float2 uv = float2(x, y);
        
        float3 p = UniformSampleSphere(uv).xyz;
        //float3 p = half3(0, 0, 1);
        p = normalize(p);
        
        float h[16] = { Y0(p), Y1(p), Y2(p), Y3(p), Y4(p), Y5(p), Y6(p), Y7(p), Y8(p), Y9(p), Y10(p), Y11(p), Y12(p), Y13(p), Y14(p), Y15(p)};
        float4 c = _CubeResource.SampleLevel(sampler_CubeResource, p, 0);
        for (int t = 0; t < 16; t++)
        {
            coefs[t] += c * h[t];
        }
    }
    RWSHBuffer[id.x] = factor * coefs[id.x];
}